package com.example.teaching_dagger2_very_simple;

import com.example.teaching_dagger2_very_simple.DaggerComponent.DaggerGameComponent;

import org.junit.Test;

import static junit.framework.Assert.assertEquals;

/**
 * Created by Albrtx on 28/11/2017.
 * TESTING DAGGER 2!
 * The following Unit Test shows how to inject the GameData into our newly created
 * GameSession using the Dagger generated Component.
 */

public class GameSessionTest {
    /*
    1.- DaggerGameComponent is generated by Dagger including the create() function.
    2.- It will create a GameComponent implementation, in which we can call inject() with our GameSession.
    3.- The inject() method will take care to inject all the defined dependencies for that object.
    4.- Finally we can see how the session.data object has been set.
    */
    @Test
    public void testGameSession(){
        GameSession session = new GameSession();
        DaggerGameComponent.create().inject(session);
        assertEquals("Hello Dagger", session.data.hello);
    }
}
